version: 0.2

phases:
  pre_build:
    commands:
      - echo installing trivy...
      - rpm -ivh https://github.com/aquasecurity/trivy/releases/download/v0.28.0/trivy_0.28.0_Linux-64bit.rpm

      - echo Logging in to Amazon ECR...
      - IMAGE_TAG=$(date +%Y-%m-%d.%H.%M.%S).$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)
      - ECR_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME    
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      
  build:
    commands:
      - echo Build started on `date`
      - echo image uri:tag is $ECR_URI:$IMAGE_TAG
      - echo Building the Docker image...          
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ECR_URI:$IMAGE_TAG    
      - echo Build completed on `date`  
  post_build:
    commands:
      - echo scanning image with trivy...
      - trivy image --no-progress --exit-code 1 --severity CRITICAL $IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Pushing the Docker image...
      - docker push $ECR_URI:$IMAGE_TAG 
      - sed -i 's@CONTAINER_IMAGE@'"$ECR_URI:$IMAGE_TAG"'@' deploy/manifests/demo-deployment.yml

artifacts:
  files: 
    - deployspec.yml
    - deploy/manifests/*   
